// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CarDetail struct {
	ID          int32
	DriverId    pgtype.Int4
	Make        pgtype.Text
	Model       pgtype.Text
	PlateNumber pgtype.Text
	Vin         pgtype.Text
	ImageUrl    pgtype.Text
}

type Driver struct {
	ID           int32
	Email        pgtype.Text
	Password     pgtype.Text
	LastLocation pgtype.Point
}

type Trip struct {
	ID                          int32
	UserId                      pgtype.Int4
	DriverId                    pgtype.Int4
	TransactionId               pgtype.Int4
	PickUpLocation              pgtype.Point
	Destination                 pgtype.Point
	CurrentTripLocation         pgtype.Point
	CurrentTripLocationFromUser pgtype.Point
	TripStartedAt               interface{}
	TripEndedAt                 interface{}
}

type User struct {
	ID       int32
	Email    pgtype.Text
	Password pgtype.Text
}

type Wallet struct {
	ID         int32
	UserId     pgtype.Int4
	Balance    pgtype.Int8
	LastFunded interface{}
}

type WalletTransaction struct {
	ID       int32
	WalletId pgtype.Int4
	Amount   pgtype.Int8
	Type     pgtype.Text
}
