// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: trip.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO "trip" (
    "userId",
    "driverId",
    "transactionId",
    "pickUpLocation",
    "destination",
    "currentTripLocation"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, "userId", "driverId", "transactionId", "pickUpLocation", destination, "currentTripLocation", "currentTripLocationFromUser", "tripStartedAt", "tripEndedAt"
`

type CreateTripParams struct {
	UserId              pgtype.Int4
	DriverId            pgtype.Int4
	TransactionId       pgtype.Int4
	PickUpLocation      pgtype.Point
	Destination         pgtype.Point
	CurrentTripLocation pgtype.Point
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserId,
		arg.DriverId,
		arg.TransactionId,
		arg.PickUpLocation,
		arg.Destination,
		arg.CurrentTripLocation,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.DriverId,
		&i.TransactionId,
		&i.PickUpLocation,
		&i.Destination,
		&i.CurrentTripLocation,
		&i.CurrentTripLocationFromUser,
		&i.TripStartedAt,
		&i.TripEndedAt,
	)
	return i, err
}

const updateTripLocationByDriver = `-- name: UpdateTripLocationByDriver :one
UPDATE "trip" SET "currentTripLocation"=$1 WHERE id=$2 AND "driverId"=$3 RETURNING id, "userId", "driverId", "transactionId", "pickUpLocation", destination, "currentTripLocation", "currentTripLocationFromUser", "tripStartedAt", "tripEndedAt"
`

type UpdateTripLocationByDriverParams struct {
	CurrentTripLocation pgtype.Point
	ID                  int32
	DriverId            pgtype.Int4
}

func (q *Queries) UpdateTripLocationByDriver(ctx context.Context, arg UpdateTripLocationByDriverParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripLocationByDriver, arg.CurrentTripLocation, arg.ID, arg.DriverId)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.DriverId,
		&i.TransactionId,
		&i.PickUpLocation,
		&i.Destination,
		&i.CurrentTripLocation,
		&i.CurrentTripLocationFromUser,
		&i.TripStartedAt,
		&i.TripEndedAt,
	)
	return i, err
}

const updateTripLocationByUser = `-- name: UpdateTripLocationByUser :one
UPDATE "trip" SET "currentTripLocationFromUser"=$1 WHERE id=$2 AND "userId"=$3 RETURNING id, "userId", "driverId", "transactionId", "pickUpLocation", destination, "currentTripLocation", "currentTripLocationFromUser", "tripStartedAt", "tripEndedAt"
`

type UpdateTripLocationByUserParams struct {
	CurrentTripLocationFromUser pgtype.Point
	ID                          int32
	UserId                      pgtype.Int4
}

func (q *Queries) UpdateTripLocationByUser(ctx context.Context, arg UpdateTripLocationByUserParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripLocationByUser, arg.CurrentTripLocationFromUser, arg.ID, arg.UserId)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.DriverId,
		&i.TransactionId,
		&i.PickUpLocation,
		&i.Destination,
		&i.CurrentTripLocation,
		&i.CurrentTripLocationFromUser,
		&i.TripStartedAt,
		&i.TripEndedAt,
	)
	return i, err
}
