// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: trip.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO "trip" (
    "userId",
    "driverId",
    "transactionId",
    "pickUpLocation",
    "destination",
    "currentTripLocation"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, "userId", "driverId", "transactionId", "pickUpLocation", destination, "currentTripLocation", "tripStartedAt", "tripEndedAt"
`

type CreateTripParams struct {
	UserId              pgtype.Int4
	DriverId            pgtype.Int4
	TransactionId       pgtype.Int4
	PickUpLocation      pgtype.Point
	Destination         pgtype.Point
	CurrentTripLocation pgtype.Point
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserId,
		arg.DriverId,
		arg.TransactionId,
		arg.PickUpLocation,
		arg.Destination,
		arg.CurrentTripLocation,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.DriverId,
		&i.TransactionId,
		&i.PickUpLocation,
		&i.Destination,
		&i.CurrentTripLocation,
		&i.TripStartedAt,
		&i.TripEndedAt,
	)
	return i, err
}
