// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: wallet_transaction.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO "wallet_transactions" (
    "walletId",
    "amount",
    "type"
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, "walletId", amount, type
`

type CreateWalletTransactionParams struct {
	WalletId pgtype.Int4
	Amount   pgtype.Int8
	Type     pgtype.Text
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction, arg.WalletId, arg.Amount, arg.Type)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletId,
		&i.Amount,
		&i.Type,
	)
	return i, err
}
